
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dv2_postgres'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'dv2_postgres'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# roger, added:
# https://automate-dv.readthedocs.io/en/latest/worked_example/we_setup/
# (old records will be ignored due to rowhash check)
vars:
  load_date: '2000-01-01'
  hash: SHA # sha-256
  hash_content_casing: 'DISABLED'


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  dv2_postgres:
    raw_stage:
      +materialized: view
      +tags:
        - 'raw'
    stage:
      +materialized: view
      +tags:
        - 'stage'
      +enabled: true
    silver_rv:
      +schema: silver_rv
      +materialized: incremental
      hubs:
        +tags:
          - 'hub'
      links:
        +tags:
          - 'link'
      sats:
        +tags:
          - 'satellite'
      t_links:
        +tags:
          - 't_link'
      references:
        +materialized: table
        +tags:
          - 'reference'
    silver_bv:
      +schema: silver_bv
      +materialized: incremental
      views:
        +materialized: view
        +tags:
          - 'view'
      bridges:
        +tags:
          - 'bridge'
      pits:
        +tags:
          - 'pit'
    gold_im:
      +schema: gold_im
      +materialized: incremental
      marts:
        +tags:
          - 'mart'
        d_date:
          +enabled: true
        f_sales:
          +enabled: true