-- simulate a patch view for data correction
-- eg. bug in source system (correct user names)

select
	-- field list generated by DBeaver
	-- after typing "t.*" hit control+space
	-- then apply "format|format SQL" from editor's context menu
	t.hk_customer_snapshot,
	t.hk_customer,
	t.cst_customer_no,
	t.load_ts,
	t.loadend_ts,
	t.cst_rowid,
	t.cst_created_at,
	t.usr_created_by,
	-- jira-12345:
	case
		when t.cst_created_at between to_date('2011-01-01', 'yyyy-mm-dd') and to_date('2020-02-15', 'yyyy-mm-dd') then
			case
				when strpos(t.usr_created_by_login_name, '-') > 1 then
            		upper(substring(t.usr_created_by_login_name, 1, strpos(t.usr_created_by_login_name, '-') - 1))
			end
		else
			t.usr_created_by_login_name
	end as usr_created_by_login_name,
	t.cst_modified_at,
	t.usr_modified_by,
    -- jira-12345:
	case
		when t.cst_modified_at between to_date('2011-01-01', 'yyyy-mm-dd') and to_date('2020-02-15', 'yyyy-mm-dd') then
			case
				when strpos(t.usr_modified_by_login_name, '-') > 1 then
            		upper(substring(t.usr_modified_by_login_name, 1, strpos(t.usr_modified_by_login_name, '-') - 1))
			end
		else
			t.usr_modified_by_login_name
	end as usr_modified_by_login_name,
	t.cst_deleted_at,
	t.usr_deleted_by,
    -- jira-12345:
	case
		when t.cst_deleted_at between to_date('2011-01-01', 'yyyy-mm-dd') and to_date('2020-02-15', 'yyyy-mm-dd') then
			case
				when strpos(t.usr_deleted_by_login_name, '-') > 1 then
            		upper(substring(t.usr_deleted_by_login_name, 1, strpos(t.usr_deleted_by_login_name, '-') - 1))
			end
		else
			t.usr_deleted_by_login_name
	end as usr_deleted_by_login_name,
	t.cod_gender,
	t.txt_gender_en,
	t.cst_first_name,
	t.cst_last_name,
	t.cst_birth_date,
	t.cod_language,
	t.txt_language_en,
	t.cst_culture,
	t.cst_credit_limit,
	t.cst_remark,
	t.cst_attr1,
	t.cst_attr2,
	t.cst_attr3,
	t.cod_source,
	t.txt_source_en,
	t.cst_attr_int,
	t.cst_attr_str,
	t.cod_level,
	t.txt_level_en,
	-- optional: patch infos
	array['jira-1000', 'jira-2000', 'jira-3000']::text[] as dwh_applied_issues
from {{ ref('fd_customer') }} t
--where t.hk_customer = 'FE69100DB52F4EA1A1982D96E779A8D9E31095F2824D86237EEAE4208DD07369'